# ==============================================================
# ML Feature Store — Dockerfile
# ==============================================================
# Builds a single image used by three services:
#   - api      → uvicorn src.api:app (default CMD)
#   - producer → python src/producer.py (overridden in compose)
#   - consumer → python src/consumer.py (overridden in compose)
#
# Build context is the project root (feature-store/).
# All paths are relative to WORKDIR /app.
# ==============================================================

# ── Stage: Base image ──────────────────────────────────────────
# python:3.11-slim = Debian Bullseye with Python 3.11, stripped of
# docs/man pages/test files. ~50MB vs ~900MB for the full image.
FROM python:3.11-slim

# ── Metadata labels (visible in `docker inspect`) ─────────────
LABEL maintainer="ml-team"
LABEL description="ML Feature Store — Fraud Detection Service"
LABEL version="1.0.0"

# ── Build-time best practices ──────────────────────────────────
# PYTHONDONTWRITEBYTECODE: Don't create .pyc files in the container
#   (saves disk space, no benefit for a short-lived container)
# PYTHONUNBUFFERED: Force stdout/stderr to flush immediately
#   (critical for seeing logs in `docker compose logs` in real-time)
ENV PYTHONDONTWRITEBYTECODE=1 \
    PYTHONUNBUFFERED=1 \
    # Set the working directory as an env var too so scripts can reference it
    APP_HOME=/app

# ── System dependencies ────────────────────────────────────────
# We need:
#   gcc, libpq-dev  → required to compile psycopg2-binary's C extension
#   curl            → used by the Docker health check (GET /health)
#   netcat-openbsd  → optional, useful for debugging network connectivity
# Clean up apt cache in the same layer to keep image size minimal
RUN apt-get update && apt-get install -y --no-install-recommends \
        gcc \
        libpq-dev \
        curl \
        netcat-openbsd \
    && rm -rf /var/lib/apt/lists/*

# ── Set working directory ──────────────────────────────────────
# All subsequent COPY, RUN, CMD instructions use /app as the base
WORKDIR ${APP_HOME}

# ── Install Python dependencies ────────────────────────────────
# IMPORTANT: Copy requirements.txt BEFORE copying source code.
# Docker caches each layer. If only source code changes (not requirements),
# Docker reuses the cached pip install layer → much faster rebuilds.
COPY requirements.txt .

RUN pip install --upgrade pip --no-cache-dir \
    && pip install --no-cache-dir -r requirements.txt

# ── Copy application source code ───────────────────────────────
# Copy src/ first (contains api.py, producer.py, consumer.py, db.py)
COPY src/ ./src/

# ── Copy pre-trained model files ──────────────────────────────
# These are the .pkl files generated by train.py.
# They are also mounted as a volume in docker-compose.yml so that
# Airflow retraining updates are picked up without rebuilding the image.
COPY models/ ./models/

# ── Copy frontend dashboard files ─────────────────────────
# Static HTML/CSS/JS for the fraud detection dashboard
COPY static/ ./static/

# ── Create a non-root user for security ───────────────────────
# Running as root inside a container is a security risk.
# If the container is compromised, the attacker has root on the host too.
RUN groupadd --gid 1000 appuser \
    && useradd --uid 1000 --gid appuser --shell /bin/bash --create-home appuser \
    && chown -R appuser:appuser ${APP_HOME}

USER appuser

# ── Expose the API port ────────────────────────────────────────
# Documents that the container listens on port 8000.
# Actual port binding happens in docker-compose.yml ("8000:8000").
EXPOSE 8000

# ── Health check (container-level) ────────────────────────────
# Docker itself checks this every 30s. If it fails 3 times in a row,
# the container is marked "unhealthy" and docker-compose restarts it.
# This is separate from the compose-level healthcheck (which is used
# for dependency ordering between services).
HEALTHCHECK --interval=30s --timeout=10s --start-period=40s --retries=3 \
    CMD curl -f http://localhost:8000/health || exit 1

# ── Default command ────────────────────────────────────────────
# Runs the FastAPI app via uvicorn.
# --host 0.0.0.0  → listen on all interfaces (not just localhost)
# --port 8000     → match the EXPOSE directive above
# --workers 1     → single worker (simple; use gunicorn for production)
# --log-level info → show request logs in docker compose logs
#
# Producer and Consumer override this CMD in docker-compose.yml:
#   command: python src/producer.py
#   command: python src/consumer.py
CMD ["uvicorn", "src.api:app", "--host", "0.0.0.0", "--port", "8000", "--log-level", "info"]
